language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
script:
- npm run build:server:production
- npm run build:client:production
- npm test
deploy:
  provider: heroku
  api_key:
    secure: PrkcXa2PNvJ/CkS0/FTc7b47/OLSdrRGwikviwSmKR1lTnz3PzKhcMcRCD278Tzk4GI/HvwDA6bEwZofrD1CSvUH9TcU+3duyfnjWvFpE+RTHpyFLPg0Q4Bu2L5rgtGzzD4K0aEyAAbGUMcdPmRry1SWCln7sBroqDChQ5fzo+kHaMPqYPbRyssozB1MqLb9cIz2U62zNUFbrUDVNV/wRaJYG2iNa99n7901OHzypBH6+iujp05Wo7BVWDdMyK5FV6bFjYyhTaItlzmTGLZz221tyhOyvCGT/pOT+BqKl4c3E3EJzGR6qYg4HZ/aD3G4XocqxhdYEZ8uHQhev9Jcr9l9oHK8/NUMjKn/morONfmzrp6DjeCyXCjDsBPr3gFW0ek1Nd3YKd8uaE7uERC0ZcRM3pR4i2TrUbRz+1yAg09Ko9vzo82yxrS8x+7bTqmHXOej/jF+Tm7RKn6YTXMZRwrxRMHMnQi+bdpK5q1YRUR1d5grOvwy1M8yyCvTBf8vzWaaDAPn6JIEZL45orM9oxIWJtrvTEzCmSuBwAASJTqLoSQ6koBmMvbJ8yM7POcPTwo5X1UHSL8T7VHuGp6MfllCJ4zGto82v70J4YC7BMdkUwP+CbcdPpciWrAj1UwmkfhM7CGOxLP8lZJTNT8ZtZeZkclLd4bYk+HM0UklFaA=
  app: rethink-it
  on:
    repo: ladyjem/rethink-it
